#!/bin/bash

# Pull-in pathogen plug-in tool
git submodule add https://github.com/tpope/vim-pathogen.git bundle/pathogen
# Fugitive is a GIT integration tool
git submodule add https://github.com/tpope/vim-fugitive.git bundle/fugitive
git submodule add https://github.com/tpope/vim-git.git bundle/git

# Add snippets to VIM
git submodule add https://github.com/msanders/snipmate.vim.git bundle/snipmate

# Quick add parenthesis, quotes, etx around a block of text
git submodule add https://github.com/tpope/vim-surround.git bundle/surround

# Multi-language syntax checking
git submodule add https://github.com/scrooloose/syntastic.git bundle/syntastic

# Mini-buffer explorer bar adds file "tabs" along the top
git submodule add https://github.com/fholgado/minibufexpl.vim.git bundle/minibufexpl

# A tool similar to grep that a blog recommended: Requires ack to be installed to run
# git submodule add https://github.com/mileszs/ack.vim.git bundle/ack

# A visual undo tree
git submodule add https://github.com/sjl/gundo.vim.git bundle/gundo

# A make utility
git submodule add https://github.com/reinh/vim-makegreen.git bundle/makegreen

# Finds all FIXE, TODO, or custom tags and incorporates them into a list
git submodule add https://github.com/vim-scripts/TaskList.vim.git bundle/tasklist

# File tree viewer
git submodule add https://github.com/scrooloose/nerdtree.git bundle/nerdtree

# Quick comment of entire lines
git submodule add https://github.com/scrooloose/nerdcommenter.git bundle/nerdcommenter

# Class browser
git submodule add https://github.com/majutsushi/tagbar.git bundle/tagbar

##### Python Specific Plugins #####
git submodule add https://github.com/fs111/pydoc.vim.git bundle/pydoc

# Provides a python test environment without having to switch back to the command prompt
git submodule add https://github.com/alfredodeza/pytest.vim.git bundle/py.test

# PlantUML syntax highlighting and shortcuts
git submodule add https://github.com/aklt/plantuml-syntax bundle/plantuml

# JEDI for python autocompletion
git submodule add https://github.com/davidhalter/jedi-vim.git bundle/jedi

##### Update all packages #####
git submodule init
git submodule update
git submodule foreach git submodule init
git submodule foreach git submodule update
