-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["brs"] = 720,
                            ["tl"] = {
                                ["dir"] = "vertical",
                                ["brs"] = 15,
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["name"] = "Tiling Frame<3>",
                                        ["managed"] = {
                                            [1] = {
                                                ["level"] = 0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["level"] = 1,
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                        ["geom"] = {
                                                            ["h"] = 858,
                                                            ["y"] = 3,
                                                            ["x"] = 3,
                                                            ["w"] = 712,
                                                        },
                                                        ["checkcode"] = 1,
                                                        ["windowid"] = 18874374,
                                                        ["bottom"] = true,
                                                    },
                                                },
                                                ["sizepolicy"] = "full",
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["h"] = 865,
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 718,
                                                },
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<1>",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                    },
                                },
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["type"] = "WSplitSplit",
                                ["tls"] = 885,
                            },
                            ["br"] = {
                                ["dir"] = "vertical",
                                ["brs"] = 450,
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["name"] = "Tiling Frame<1>",
                                        ["managed"] = {
                                            [1] = {
                                                ["level"] = 0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["level"] = 1,
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                        ["geom"] = {
                                                            ["h"] = 424,
                                                            ["y"] = 3,
                                                            ["x"] = 3,
                                                            ["w"] = 712,
                                                        },
                                                        ["checkcode"] = 2,
                                                        ["windowid"] = 16777222,
                                                        ["bottom"] = true,
                                                    },
                                                },
                                                ["sizepolicy"] = "full",
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["h"] = 430,
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 718,
                                                },
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                    },
                                },
                                ["br"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["name"] = "Tiling Frame",
                                        ["managed"] = {
                                            [1] = {
                                                ["level"] = 0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["level"] = 1,
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                        ["geom"] = {
                                                            ["h"] = 430,
                                                            ["y"] = 0,
                                                            ["x"] = 0,
                                                            ["w"] = 718,
                                                        },
                                                        ["checkcode"] = 3,
                                                        ["windowid"] = 20971644,
                                                        ["bottom"] = true,
                                                    },
                                                },
                                                ["sizepolicy"] = "full",
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["h"] = 430,
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 718,
                                                },
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<2>",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                    },
                                },
                                ["type"] = "WSplitSplit",
                                ["tls"] = 450,
                            },
                            ["type"] = "WSplitSplit",
                            ["tls"] = 720,
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["h"] = 900,
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1440,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                    },
                },
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["geom"] = {
                    ["h"] = 900,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1440,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "default",
                },
                ["name"] = "WGroupWS",
            },
            [2] = {
                ["level"] = 1,
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["geom"] = {
                            ["h"] = 480,
                            ["y"] = 360,
                            ["x"] = 640,
                            ["w"] = 640,
                        },
                        ["level"] = 1025,
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                    },
                },
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["h"] = 900,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1440,
                },
                ["unnumbered"] = true,
                ["pseudomodal"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
            },
        },
        ["type"] = "WScreen",
    },
}

