#!/bin/bash

# Recovery information for dreadnought
# The road to hell is paved with good intentions
# Should you ever need to go back a step, look here
# Last modified on 1 October 2013

# Step #1: Recover Static IP
# IP Address: 137.78.253.164
# Netmask: 255.255.255.0
# Gateway: 137.78.253.1
# DNS1: 137.78.160.9
# DNS2: 137.78.160.19

# Packages:
# aptitude - Package Manager
# gimp, inkscape - Graphics Programs
# git - Code repository
# unison - File Sync
# enigmail - PGP encryption
apt-get install aptitude
aptitude install gimp inkscape git unison enigmail

# Custom Install (used /opt):
# MATLAB (R2013a) - from JPL
# Texlive (2013) - From CTAN website

# Modified Configuration Files:
# .bashrc
# export GPGKEY=A0697566

# PGP Key Creation (Shouldn't need to redo)
# gpg --gen-key

